sudo: required
branches:
    only:
        - develop
language: node_js
node_js:
    - "8.9.3"
dist: trusty
before_install:
    - npm install -g npm@~5.6.0
    - npm install -g ionic cordova
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    - sudo apt-get update -qq
    - sudo apt-get install -qq google-chrome-stable
before_script:
    - sudo chown root /opt/google/chrome/chrome-sandbox
    - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
install:
    - npm install
script:
    - npm run test-ci #Run the Jasmine unit tests
addons:
    - chrome: 
        - stable
stage:
    - Test